### ISSUE TITLE
Can I override the ruler configuration? 

### ISSUE THREAD

**Issue by alextakitani** [Shopify/vscode-shopify-ruby#399]
I saw that the extension enforces 120, and overwrites any changes that I make to setting.json

Is there any way to set it to another value?

**Comment by alextakitani** [comment]
Hi Vinicius, thank you for taking the time to answer me. 

I'd tried to follow the steps you told me to, but after choosing  "Ruby extensions pack: Force apply defaults"
nothing happened.

I had to override the ruler setting on my settings.json, then reload the window for the popup to show up.

Then it worked fine.

Thanks for your help!

By the way, are you planning on adding "go-to-definition" to the extension?

**Comment by vinistock** [comment]
Oh, yeah, sorry I forgot about that aspect. If your current settings already matched the recommendations, then you're not prompted.

We plan on adding go to definition to the Ruby LSP. You can follow the progress on this issue https://github.com/Shopify/ruby-lsp/issues/199.
