### ISSUE TITLE
Interest in supporting this extension pack in a GitHub Codespace?

### ISSUE THREAD

**Issue by MarkBennett** [Shopify/vscode-shopify-ruby#400]
My team has been using Codespaces more and more for Ruby development (Rails w/ Postresql mostly), and I've been looking for best practices to follow. I'm not sure it's entirely in scope for this repo, but would love to know if anyone is using this successfully with GitHub Codespaces for their team?

If so, would you be willing to share your setup in this repo, so you can quickly configure a new Codespace using this extension pack? Would the maintainers be interested in that kind of contribution?

**Comment by vinistock** [comment]
I'm not super familiar with Codespaces configuration. How does it work? Would we export one from this repository and it would make it easier for everybody else to use it?

**Comment by MarkBennett** [comment]
> I'm not super familiar with Codespaces configuration. How does it work? Would we export one from this repository and it would make it easier for everybody else to use it?

So Codespaces have two parts, a json called devcontainer.json which specifies some basic env settings, and recommends extensions like this one to install. It also specifies a Docker container, or docker-compose.yml, which describes a container that the dev environment runs in.

In order to support this extension, the Docker container would need to be set up with rbenv in the path, and any dependencies needed to run the extensions in this pack installed.

In terms of sharing templates, there's a repo here on GitHub that includes templates for different development Codespaces. I'm on my phone but will post a link when I'm at my computer.

**Comment by vinistock** [comment]
My understanding is that, as long as `devcontainer.json` is configured with Ruby and the Ruby LSP / Ruby extensions pack, this should work properly in Codespaces.

Please re-open if that's not the case!
