### ISSUE TITLE
Message about uninstalling reborn.ruby and wingrunr21.vscode-ruby upon Vscode startup

### ISSUE THREAD

**Issue by obromios** [Shopify/vscode-shopify-ruby#431]
### Operating System

OSX 13.3.1

### Ruby version

3.1.3

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rvm

### Description

Looking in the .ruby-lsp Gemfile.lock, I am using ruby-lsp `0.4.5` and the extension version is `0.2.5` and Vscode says it is up to date.  When I start Vscode I see the following  message

`The Ruby LSP has fully replaced the Ruby plugin functionality. Uninstall the `rebornix.ruby` and the `wingrunr21.vscode-ruby` extensions. Click `Cleanup` to remove related configuration.   `

I have searched for the two cited extensions and can find neither.  I have clicked 'Cleanup` but the error occurs again upon startup. I am new to the extension but I am finding very useful, thank you. It is just a bit talkative upon startup.

**Comment by andyw8** [comment]
I've transferred this issue to https://github.com/Shopify/vscode-shopify-ruby since the message originates there:

https://github.com/Shopify/vscode-shopify-ruby/blob/eb2ca492b4379a8e42a033d4df406eb7827384da/src/extension.ts#L9

`rebornix.ruby` may be listed in the VS Code extension panel as just 'Ruby' – are you sure you don't have that still?

**Comment by obromios** [comment]
I have typed just 'ruby' into the extension panel, and I have

1. Ruby by Peng Li
2. Ruby by Shopify (which I assume is you guys)
3. VS code ruby

Are 1. or 3. rebornix ruby?  Should I uninstall them anyway given I am using Shopify ruby?

If it is not 1. and 3., what strings does the api use to search for these two extensions?

**Comment by andyw8** [comment]
1 is `rebornix ruby`, you can see from the URL here: https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby

You should remove 3 as well.

**Comment by obromios** [comment]
That worked thank you.
