### ISSUE TITLE
How can I add the semantic token colours to an existing theme that doesn't have them?

### ISSUE THREAD

**Issue by unikitty37** [Shopify/vscode-shopify-ruby#442]
I find the Spinel theme to be much too bright (and very distracting as a result) so I'm using [Darcula IntelliJ Theme Extended](https://github.com/diep89/darcula-intellij-theme-extended) instead. It doesn't have the semantic token colours needed for Ruby, though.

I've tried adding this to `settings.json` but it doesn't seem to make any difference to what's displayed when I open a Ruby file — I still the the same as if I hadn't added this JSON.

```json
  "editor.semanticTokenColorCustomizations": {
    "[Darcula IntelliJ Theme Extended]": {
      "enabled": true,
      "rules": {
        "variable": "#1eda7c",
        "class": {
          "foreground": "#ec7a08",
          "fontStyle": "bold"
        }
      }
    }
  },
```

(Yes, those two colours are _also_ garish, but I wanted to be sure I could see them change while I was experimenting :)

Am I actually configuring this correctly?

**Comment by vinistock** [comment]
The customizations are indeed correct. Not sure why it isn't working. Can you try changing this config?
```json
{
  "editor.semanticHighlighting.enabled": true,
}
```
Maybe the theme doesn't support semantic highlighting and your editor is configured to enable it based on theme configurations.

You can also use the token inspector to verify that you're looking at the right tokens.
- Open the command palette (CMD + SHIFT + P)
- Inspect editor tokens and scopes
- Click on a piece of code to see the assigned tokens
