### ISSUE TITLE
Ruby extension wants to set Shopify.ruby-lsp as default formatter, but then complains it can't format Ruby

### ISSUE THREAD

**Issue by unikitty37** [Shopify/vscode-shopify-ruby#443]
When I open a Ruby file, I get the error 'No configuration found for editor.defaultFormatter. Would you like to apply the suggested default ("Shopify.ruby-lsp")?'

![image](https://github.com/Shopify/vscode-shopify-ruby/assets/139183/290f9c77-0187-42fc-a41f-bf44ac52e110)

If I click Apply, then open the command palette and run `Developer: Reload Window` I get the formatter error icon in the status bar. Clicking on it shows a message saying "Formatting — Extension 'Ruby-LSP' is configured as formatter but it cannot format 'Ruby'-files'. Clicking the `Configure…` link only offers me `ruby-rubocop-revived` as a formatter.

![image](https://github.com/Shopify/vscode-shopify-ruby/assets/139183/c93f6d93-af86-4463-8565-412423db6a7b)

Why would the extension offer to set Ruby-LSP as the default formatter if it can't format Ruby? (I'm not sure if the problem is that it's offering when it shouldn't, or if VSCode thinks Ruby-LSP can't format when it can :)

**Comment by andyw8** [comment]
Hi @unikitty37, which version of the `ruby-lsp` gem is in use?

**Comment by andyw8** [comment]
Also can you try disabling the `ruby-rubocop-revived` extension.

**Comment by andyw8** [comment]
Can you try adding this your settings, if not already present:

```
  "[ruby]": {
    "editor.defaultFormatter": "Shopify.ruby-lsp"
  }
```

**Comment by vinistock** [comment]
Is `rubyLsp.formatter` configured to anything? And in the application you're using, do you have RuboCop or Syntax Tree installed to format files?

**Comment by unikitty37** [comment]
@andyw8 Thanks — that was already present in the settings.

@vinistock `rubyLsp.formatter` is configured to `rubocop`. RuboCop is installed globally; if I save a file as `/tmp/foo.rb` and run `rubocop /tmp/foo.rb`, it runs. But opening that file in VSCode and running the format command still produces "There is no formatter for 'ruby' files installed."

It also comes up with "Ruby LSP formatter is set to `rubocop` but RuboCop was not found in the bundle". This is odd, as this is just a .rb file in a folder — Bundler is not being used in this case.

I'm using rbenv, if that matters.

**Comment by vinistock** [comment]
The Ruby LSP doesn't support running RuboCop from a global installation. It must be a part of your `Gemfile` or else it just gets ignored.

The reason for this is consistency. If multiple developers are working on the same codebase and they're all running global installations of RuboCop, there's no guarantee that the developers aren't running different versions, which may lead to different formatting results. 

Additionally, if there's a version mismatch between the global installation and CI, then linting will fail on CI despite formatting being enabled in the editor.
