### ISSUE TITLE
bricks color theme

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [Shopify/vscode-shopify-ruby#561]
Hi,

I'm using this color theme: https://github.com/mrded/vscode-theme-railscasts

and after enabling the Shopify ruby extension it bricks my color theme?

How can I disable the override over my colortheme?

**Comment by vinistock** [comment]
Hello! What do you mean with "bricks my color theme"?

The Ruby LSP provides semantic highlighting information, which might change how the theme highlights your code - especially if it does not take semantic information into account.
