### ISSUE TITLE
Feature request: built-in support for syntax_suggest

### ISSUE THREAD

**Issue by swrobel** [Shopify/vscode-shopify-ruby#575]
[syntax_suggest](https://github.com/ruby/syntax_suggest) is a great feature of recent Rubies. Editor integration for it would be a welcome addition!

EDIT: Here's an example of a [plugin for solargraph](https://github.com/CKolkey/solargraph-syntax-suggest#solargraphsyntaxsuggest) that does the same as what I'm suggesting here

**Comment by vinistock** [comment]
Thank you for the feature suggestion!

The new Ruby parser [Prism](https://github.com/ruby/prism) comes with error tolerance and the Ruby LSP uses that information to surface them in the editor.

The Prism team has mostly been focusing on compatibility with Ruby for now, so there's a lot to improve in terms of how the errors are reported and the correctness of the errors.

That said, when efforts are put into Prism to enhance the error tolerance information, is there any advantage to using Syntax suggest?

My understanding is that it shows syntax errors with suggestions on how to fix it, which will eventually be handled by Prism itself. If this is the case, then there's nothing for us to do, all of the work is on the Prism side.

**Comment by swrobel** [comment]
I don't really know anything about Prism, other than that it's brand new, or whether this extension is using it (I don't see any references to it in the repo).

You are correct about the purpose of syntax_suggest. It is ready to be used now, which I think is a major advantage over Prism, based on my understanding of your summary of the state of its syntax error feedback.
