### ISSUE TITLE
Syntax highlighting breaks on non-Spinel themes

### ISSUE THREAD

**Issue by noahgregory-basis** [Shopify/vscode-shopify-ruby#578]
After reading #562, I was a bit concerned about using these extensions for general development, but they appear fine to use right now. I've just noticed, though, syntax highlighting sometimes breaks in other color themes. Below is a `Regexp` to match a Japanese date format in the built-in Red color theme. It does _not_ appear like this without the Ruby extensions installed. To note, the Spinel themes that comes with the extensions do not appear to have this issue.

<img width="353" alt="Screenshot 2024-02-01 at 17 10 12" src="https://github.com/Shopify/vscode-shopify-ruby/assets/144285599/ab2e5e53-aefb-45a6-a9d1-615c93ebcffa">

**Comment by vinistock** [comment]
> I was a bit concerned about using these extensions for general development, but they appear fine to use right now

They are all for general development. That issue contains a misunderstanding.

> though, syntax highlighting sometimes breaks in other color themes. 

It's not related to themes, it's actually a bug with handling multibyte characters: https://github.com/Shopify/ruby-lsp/issues/1162. You can see that the highlighting is offset by a few characters, which is the number of extra bytes in the Japanese characters.

I'll close this issue to keep discussions centralized in that one.
