### ISSUE TITLE
Publish this extension on OpenVSX as well

### ISSUE THREAD

**Issue by tomash** [Shopify/vscode-shopify-ruby#646]
Some popular Linux distibutions like Arch and Manjaro by default ship VSCode build that does not use official Visual Studio Marketplace but points to OpenVSX instead. For more context see:

* https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178
* https://www.eclipse.org/community/eclipse_newsletter/2020/march/1.php

Please publish this extension to OpenVSX as well, so that it's available to developers using aforementioned builds, instead of having to manually install from VSIX file. You do already publish Ruby LSP there (kudos!). And yes, I need it for the awesome Spinel theme.

**Comment by andyw8** [comment]
We've added the configuration for this, so the next release of this extension should be available on OpenVSX.
